# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/3458BAEA4EE0CEE8/Projects/dino2-unpacker

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/3458BAEA4EE0CEE8/Projects/dino2-unpacker

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/3458BAEA4EE0CEE8/Projects/dino2-unpacker/CMakeFiles /mnt/3458BAEA4EE0CEE8/Projects/dino2-unpacker//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/3458BAEA4EE0CEE8/Projects/dino2-unpacker/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dino2-unpacker

# Build rule for target.
dino2-unpacker: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dino2-unpacker
.PHONY : dino2-unpacker

# fast build rule for target.
dino2-unpacker/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dino2-unpacker.dir/build.make CMakeFiles/dino2-unpacker.dir/build
.PHONY : dino2-unpacker/fast

converter/converter.o: converter/converter.cpp.o

.PHONY : converter/converter.o

# target to build an object file
converter/converter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dino2-unpacker.dir/build.make CMakeFiles/dino2-unpacker.dir/converter/converter.cpp.o
.PHONY : converter/converter.cpp.o

converter/converter.i: converter/converter.cpp.i

.PHONY : converter/converter.i

# target to preprocess a source file
converter/converter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dino2-unpacker.dir/build.make CMakeFiles/dino2-unpacker.dir/converter/converter.cpp.i
.PHONY : converter/converter.cpp.i

converter/converter.s: converter/converter.cpp.s

.PHONY : converter/converter.s

# target to generate assembly for a file
converter/converter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dino2-unpacker.dir/build.make CMakeFiles/dino2-unpacker.dir/converter/converter.cpp.s
.PHONY : converter/converter.cpp.s

converter/paletteconverter.o: converter/paletteconverter.cpp.o

.PHONY : converter/paletteconverter.o

# target to build an object file
converter/paletteconverter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dino2-unpacker.dir/build.make CMakeFiles/dino2-unpacker.dir/converter/paletteconverter.cpp.o
.PHONY : converter/paletteconverter.cpp.o

converter/paletteconverter.i: converter/paletteconverter.cpp.i

.PHONY : converter/paletteconverter.i

# target to preprocess a source file
converter/paletteconverter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dino2-unpacker.dir/build.make CMakeFiles/dino2-unpacker.dir/converter/paletteconverter.cpp.i
.PHONY : converter/paletteconverter.cpp.i

converter/paletteconverter.s: converter/paletteconverter.cpp.s

.PHONY : converter/paletteconverter.s

# target to generate assembly for a file
converter/paletteconverter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dino2-unpacker.dir/build.make CMakeFiles/dino2-unpacker.dir/converter/paletteconverter.cpp.s
.PHONY : converter/paletteconverter.cpp.s

dechunker.o: dechunker.cpp.o

.PHONY : dechunker.o

# target to build an object file
dechunker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dino2-unpacker.dir/build.make CMakeFiles/dino2-unpacker.dir/dechunker.cpp.o
.PHONY : dechunker.cpp.o

dechunker.i: dechunker.cpp.i

.PHONY : dechunker.i

# target to preprocess a source file
dechunker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dino2-unpacker.dir/build.make CMakeFiles/dino2-unpacker.dir/dechunker.cpp.i
.PHONY : dechunker.cpp.i

dechunker.s: dechunker.cpp.s

.PHONY : dechunker.s

# target to generate assembly for a file
dechunker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dino2-unpacker.dir/build.make CMakeFiles/dino2-unpacker.dir/dechunker.cpp.s
.PHONY : dechunker.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dino2-unpacker.dir/build.make CMakeFiles/dino2-unpacker.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dino2-unpacker.dir/build.make CMakeFiles/dino2-unpacker.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dino2-unpacker.dir/build.make CMakeFiles/dino2-unpacker.dir/main.cpp.s
.PHONY : main.cpp.s

unpacker/armorunpacker.o: unpacker/armorunpacker.cpp.o

.PHONY : unpacker/armorunpacker.o

# target to build an object file
unpacker/armorunpacker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dino2-unpacker.dir/build.make CMakeFiles/dino2-unpacker.dir/unpacker/armorunpacker.cpp.o
.PHONY : unpacker/armorunpacker.cpp.o

unpacker/armorunpacker.i: unpacker/armorunpacker.cpp.i

.PHONY : unpacker/armorunpacker.i

# target to preprocess a source file
unpacker/armorunpacker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dino2-unpacker.dir/build.make CMakeFiles/dino2-unpacker.dir/unpacker/armorunpacker.cpp.i
.PHONY : unpacker/armorunpacker.cpp.i

unpacker/armorunpacker.s: unpacker/armorunpacker.cpp.s

.PHONY : unpacker/armorunpacker.s

# target to generate assembly for a file
unpacker/armorunpacker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dino2-unpacker.dir/build.make CMakeFiles/dino2-unpacker.dir/unpacker/armorunpacker.cpp.s
.PHONY : unpacker/armorunpacker.cpp.s

unpacker/dechunkerunpacker.o: unpacker/dechunkerunpacker.cpp.o

.PHONY : unpacker/dechunkerunpacker.o

# target to build an object file
unpacker/dechunkerunpacker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dino2-unpacker.dir/build.make CMakeFiles/dino2-unpacker.dir/unpacker/dechunkerunpacker.cpp.o
.PHONY : unpacker/dechunkerunpacker.cpp.o

unpacker/dechunkerunpacker.i: unpacker/dechunkerunpacker.cpp.i

.PHONY : unpacker/dechunkerunpacker.i

# target to preprocess a source file
unpacker/dechunkerunpacker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dino2-unpacker.dir/build.make CMakeFiles/dino2-unpacker.dir/unpacker/dechunkerunpacker.cpp.i
.PHONY : unpacker/dechunkerunpacker.cpp.i

unpacker/dechunkerunpacker.s: unpacker/dechunkerunpacker.cpp.s

.PHONY : unpacker/dechunkerunpacker.s

# target to generate assembly for a file
unpacker/dechunkerunpacker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dino2-unpacker.dir/build.make CMakeFiles/dino2-unpacker.dir/unpacker/dechunkerunpacker.cpp.s
.PHONY : unpacker/dechunkerunpacker.cpp.s

unpacker/doorunpacker.o: unpacker/doorunpacker.cpp.o

.PHONY : unpacker/doorunpacker.o

# target to build an object file
unpacker/doorunpacker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dino2-unpacker.dir/build.make CMakeFiles/dino2-unpacker.dir/unpacker/doorunpacker.cpp.o
.PHONY : unpacker/doorunpacker.cpp.o

unpacker/doorunpacker.i: unpacker/doorunpacker.cpp.i

.PHONY : unpacker/doorunpacker.i

# target to preprocess a source file
unpacker/doorunpacker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dino2-unpacker.dir/build.make CMakeFiles/dino2-unpacker.dir/unpacker/doorunpacker.cpp.i
.PHONY : unpacker/doorunpacker.cpp.i

unpacker/doorunpacker.s: unpacker/doorunpacker.cpp.s

.PHONY : unpacker/doorunpacker.s

# target to generate assembly for a file
unpacker/doorunpacker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dino2-unpacker.dir/build.make CMakeFiles/dino2-unpacker.dir/unpacker/doorunpacker.cpp.s
.PHONY : unpacker/doorunpacker.cpp.s

unpacker/itemunpacker.o: unpacker/itemunpacker.cpp.o

.PHONY : unpacker/itemunpacker.o

# target to build an object file
unpacker/itemunpacker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dino2-unpacker.dir/build.make CMakeFiles/dino2-unpacker.dir/unpacker/itemunpacker.cpp.o
.PHONY : unpacker/itemunpacker.cpp.o

unpacker/itemunpacker.i: unpacker/itemunpacker.cpp.i

.PHONY : unpacker/itemunpacker.i

# target to preprocess a source file
unpacker/itemunpacker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dino2-unpacker.dir/build.make CMakeFiles/dino2-unpacker.dir/unpacker/itemunpacker.cpp.i
.PHONY : unpacker/itemunpacker.cpp.i

unpacker/itemunpacker.s: unpacker/itemunpacker.cpp.s

.PHONY : unpacker/itemunpacker.s

# target to generate assembly for a file
unpacker/itemunpacker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dino2-unpacker.dir/build.make CMakeFiles/dino2-unpacker.dir/unpacker/itemunpacker.cpp.s
.PHONY : unpacker/itemunpacker.cpp.s

unpacker/pxlunpacker.o: unpacker/pxlunpacker.cpp.o

.PHONY : unpacker/pxlunpacker.o

# target to build an object file
unpacker/pxlunpacker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dino2-unpacker.dir/build.make CMakeFiles/dino2-unpacker.dir/unpacker/pxlunpacker.cpp.o
.PHONY : unpacker/pxlunpacker.cpp.o

unpacker/pxlunpacker.i: unpacker/pxlunpacker.cpp.i

.PHONY : unpacker/pxlunpacker.i

# target to preprocess a source file
unpacker/pxlunpacker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dino2-unpacker.dir/build.make CMakeFiles/dino2-unpacker.dir/unpacker/pxlunpacker.cpp.i
.PHONY : unpacker/pxlunpacker.cpp.i

unpacker/pxlunpacker.s: unpacker/pxlunpacker.cpp.s

.PHONY : unpacker/pxlunpacker.s

# target to generate assembly for a file
unpacker/pxlunpacker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dino2-unpacker.dir/build.make CMakeFiles/dino2-unpacker.dir/unpacker/pxlunpacker.cpp.s
.PHONY : unpacker/pxlunpacker.cpp.s

unpacker/unpacker.o: unpacker/unpacker.cpp.o

.PHONY : unpacker/unpacker.o

# target to build an object file
unpacker/unpacker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dino2-unpacker.dir/build.make CMakeFiles/dino2-unpacker.dir/unpacker/unpacker.cpp.o
.PHONY : unpacker/unpacker.cpp.o

unpacker/unpacker.i: unpacker/unpacker.cpp.i

.PHONY : unpacker/unpacker.i

# target to preprocess a source file
unpacker/unpacker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dino2-unpacker.dir/build.make CMakeFiles/dino2-unpacker.dir/unpacker/unpacker.cpp.i
.PHONY : unpacker/unpacker.cpp.i

unpacker/unpacker.s: unpacker/unpacker.cpp.s

.PHONY : unpacker/unpacker.s

# target to generate assembly for a file
unpacker/unpacker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dino2-unpacker.dir/build.make CMakeFiles/dino2-unpacker.dir/unpacker/unpacker.cpp.s
.PHONY : unpacker/unpacker.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... dino2-unpacker"
	@echo "... converter/converter.o"
	@echo "... converter/converter.i"
	@echo "... converter/converter.s"
	@echo "... converter/paletteconverter.o"
	@echo "... converter/paletteconverter.i"
	@echo "... converter/paletteconverter.s"
	@echo "... dechunker.o"
	@echo "... dechunker.i"
	@echo "... dechunker.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... unpacker/armorunpacker.o"
	@echo "... unpacker/armorunpacker.i"
	@echo "... unpacker/armorunpacker.s"
	@echo "... unpacker/dechunkerunpacker.o"
	@echo "... unpacker/dechunkerunpacker.i"
	@echo "... unpacker/dechunkerunpacker.s"
	@echo "... unpacker/doorunpacker.o"
	@echo "... unpacker/doorunpacker.i"
	@echo "... unpacker/doorunpacker.s"
	@echo "... unpacker/itemunpacker.o"
	@echo "... unpacker/itemunpacker.i"
	@echo "... unpacker/itemunpacker.s"
	@echo "... unpacker/pxlunpacker.o"
	@echo "... unpacker/pxlunpacker.i"
	@echo "... unpacker/pxlunpacker.s"
	@echo "... unpacker/unpacker.o"
	@echo "... unpacker/unpacker.i"
	@echo "... unpacker/unpacker.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

